defaults:
  - clips: high_interaction
  - preprocessing: default
  - feature_extraction: default
  - autoencoder: default
  - splat: default
  - graph_extraction: default
  - _self_

cholec80_root: data/cholec80
cholecseg8k_root: data/cholecseg8k
cholect50_root: data/cholect50
preprocessed_root: data/preprocessed_high_interaction_single_frame_pc
output_root: output/high_interaction_single_frame_pc/dl_${splat.dynamic_language}

hydra:
  job:
    chdir: false